name: CI/CD for time-app deploy to ec2

on:
    push: 
        branches: ["main"]

jobs:
    build-and-deploy:
        strategy:
          matrix:
            os: [ubuntu-latest]
            node-version: ["24.15.0"]

        runs-on: ${{matrix.os}}
        steps:
            - name: Cloning Repository
              uses: actions/checkout@v6
            
            - name: Install Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v6
              with:
                node-version: ${{matrix.node-version}}

            - name: API Dependency Install
              working-directory: ./api
              run: npm install 

    
